hs.hotkey.bind({"cmd"}, "f10", function()
  local output = hs.audiodevice.defaultOutputDevice()
  local muted = output:muted()
  output:setMuted(not muted)
end)

hs.hotkey.bind({"cmd"}, "f11", function()
  local output = hs.audiodevice.defaultOutputDevice()
  local currentVolume = output:outputVolume()
  output:setMuted(false)
  output:setOutputVolume(currentVolume - 10)
end)

hs.hotkey.bind({"cmd"}, "f12", function()
  local output = hs.audiodevice.defaultOutputDevice()
  local currentVolume = output:outputVolume()
  output:setMuted(false)
  output:setOutputVolume(currentVolume + 10)
end)
